### ISSUE TITLE
type: __shini_parse_error: not found

### ISSUE THREAD

**Issue by JackyShu** [wallyhall/shini#1]
Hi Shini,

When I ran example.sh, I got the following error.
Do we have to define __shini_parse_error?

Thanks,

"
Parsing...

grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 0:
  `[Section1]`
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 1:
  `name=John Doe`
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 2:
  `organization=Acme Widgets Inc.`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 4:
  `[Section2]`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 6:
  `server=10.1.2.3`
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 7:
  `port=80`
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 8:
  `file="payroll.dat"`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 10:
  `this_value_was_in_hex = 0x2223`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 12:
  `[Another_Section]`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 15:
  `test_key_22=test test test`
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 16:
  `var_with_leading_whitespace=value`
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 17:
  `whitespace_test  =  lots of whitespace`
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 18:
  `quoted_quotespace =   "  lots more whitespace  "`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 20:
  `[Whitespace_Section]`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 22:
  `null_value=`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 24:
  `test="abc" ; inline comment`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 26:
  `[empty_section1]`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
./shini.sh: line 9: type: __shini_parse_error: not found
shini: Unable to parse line 28:
  `[empty_section2]`
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end
grep: Invalid range end

Complete.
"

**Comment by wallyhall** [comment]
Hi there,

What bash and grep version are you using?

bash --version
grep --version

**Comment by JackyShu** [comment]
Hi,

bash: 4.1.2
grep: 2.6.3

Thanks,

**Comment by wallyhall** [comment]
OK - the problem seems to have been to do with older versions of grep handling regex character classes in a different manner.
Can you try with the latest revision?

**Comment by JackyShu** [comment]
Hi Shini,

I upgraded grep to 2.21, still having the same error. Any thoughts?

Thanks,

Jacky

**Comment by JackyShu** [comment]
If I replace "grep -qe" with "grep -P", I got 

"
Parsing...

[Section1]
sed: -e expression #1, char 55: Invalid range end
name=John Doe
sed: -e expression #1, char 54: Invalid range end
sed: -e expression #1, char 93: Invalid range end
  .=''
organization=Acme Widgets Inc.
sed: -e expression #1, char 54: Invalid range end
sed: -e expression #1, char 93: Invalid range end
  .=''
"

So now the problem is sed.

**Comment by JackyShu** [comment]
Looks hyphen - caused the problem.
It works fine if I removed it.from $RX_EKY and $RX_SECTION

#  RX_KEY='[a-zA-Z0-9\-_]'
  RX_KEY='[a-zA-Z0-9_]'
  RX_VALUE="[^;\"]"
#  RX_SECTION='[a-zA-Z0-9\-_]'
  RX_SECTION='[a-zA-Z0-9_]'

**Comment by wallyhall** [comment]
Sorry regarding 'latest version' I meant of shini - the hyphen indeed appears to be the problem, I moved it in the latest code version to fix the problem.

Tested on a Debian box with a very similar grep version to you - and it started working for me (having reproduced the problem there).

I'm hopeful if you pull the latest code, it'll work for you too...

**Comment by JackyShu** [comment]
Hi Shini,

The latest code works!

Thank you!
