### ISSUE TITLE
Add write support

### ISSUE THREAD

**Issue by cmcqueen** [wallyhall/shini#2]
This utility is a great idea, and I would find it useful. But I also have a need for write support. Do you expect to have write support soon? I see the README mentions it for v2.

**Comment by wallyhall** [comment]
I do - I'm afraid it's as always a matter of having no spare time to work on it though!
I've an experimental branch with a basic implementation begun, I'll take a look tonight and see if I can't get something basic out this week...

Thanks for showing your interest, it certainly helps motivate completion.

**Comment by wallyhall** [comment]
I've finished off what I had started, which I think is passable as "alpha" write support.
It's going to be buggy, I'd appreciate feedback.  I'll start updating the documentation now...
